# Site settings
title: Hedfan
header-img: img/home-bg.jpg
email: owain@hedfan.uk
description: "A blog about my own personal love affair with flight."
baseurl: ""
url: "http://hedfan.uk"
twitter_username: AnturGyffrous
github_username:  AnturGyffrous

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
