# Site settings
title: Hedfan
header-img: img/home-bg.jpg
email: owain@hedfan.uk
description: "A blog about my own personal love affair with flight."
baseurl: ""
url: "http://hedfan.uk"
twitter_username: AnturGyffrous
github_username:  AnturGyffrous
author: Owain Abraham-Williams

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate,jekyll-redirect-from]